### ISSUE TITLE
Option to set current event

### ISSUE THREAD

**Issue by brunowego** [eowo/angular-horizontal-timeline#1]
You have a nice plugin here, congrats for that! What you think about add a option to set a current event?

**Comment by Balaji-Ramseshkumar** [comment]
Can I get this same plugin for angular 5

**Comment by eowo** [comment]
@brunowego Sorry for my late reply. Nice idea but I don't have any free time for this.

**Comment by eowo** [comment]
@Jilaba Sorry but I don't convert the plugin to angular 5.
